FROM tomcat:9.0-jdk11-openjdk

RUN ["mkdir", "-p", "/opt/urebal/engine_libs"]
RUN ["mkdir", "-p", "/opt/urebal/urebal_config_files"]
RUN ["mkdir", "-p", "/opt/urebal/support_zip"]

COPY  ./release-package/Linux/ /opt/urebal/engine_libs/
RUN ["ls", "/opt/urebal/engine_libs"]

COPY  ./release-package/serviceweb.war /tmp/softpak_libs/
COPY  ./release-package/urebal_config_files/ /opt/urebal/urebal_config_files/
RUN ["ls", "/opt/urebal/urebal_config_files/"]

WORKDIR /opt
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "awscli", "-y"]

RUN ["chmod", "+x", "/usr/local/tomcat/bin/catalina.sh"]
RUN ["chmod", "+x", "/usr/local/tomcat/bin/startup.sh"]

RUN ["rm",  "-Rf", "/usr/local/tomcat/webapps/ROOT"]
RUN ["cp", "/tmp/softpak_libs/serviceweb.war", "/usr/local/tomcat/webapps/"]

EXPOSE 80 443 8080

ENTRYPOINT  ["/usr/local/tomcat/bin/startup.sh", "run"]
