FROM tomcat:9.0-jdk11-openjdk

RUN ["mkdir", "-p", "/opt/urebal/engine_libs"]
RUN ["mkdir", "-p", "/opt/urebal/urebal_config_files"]
RUN ["mkdir", "-p", "/opt/urebal/support_zip"]

COPY  ./rulebase-be/cpp_artifact/Linux/ /opt/urebal/engine_libs/
RUN ["ls", "/opt/urebal/engine_libs"]

COPY  ./serviceweb/target/serviceweb.war /tmp/softpak_libs/
COPY  ./urebal_config_files/ /opt/urebal/urebal_config_files/
RUN ["ls", "/opt/urebal/urebal_config_files/"]

#COPY  ./telegraf-1.12.1_linux_amd64.tar.gz /tmp/softpak_libs/
#COPY  ./serviceweb_telegraf.conf /tmp/softpak_libs/
#COPY  ./catalina.sh /tmp/softpak_libs/
#COPY  ./startup.sh /tmp/softpak_libs/

WORKDIR /opt
RUN ["apt-get", "update"]
RUN ["apt-get", "install", "awscli", "-y"]
#RUN ["tar", "-xf", "telegraf-1.12.1_linux_amd64.tar.gz"]

#RUN ["cp", "-R", "/tmp/softpak_libs/telegraf/usr", "/"]
#RUN ["cp", "-R", "/tmp/softpak_libs/telegraf/var", "/"]
#RUN ["cp", "-R", "/tmp/softpak_libs/telegraf/etc", "/"]

#RUN ["cp", "/tmp/softpak_libs/catalina.sh", "/usr/local/tomcat/bin/"]
#RUN ["cp", "/tmp/softpak_libs/startup.sh", "/usr/local/tomcat/bin/"]

RUN ["chmod", "+x", "/usr/local/tomcat/bin/catalina.sh"]
RUN ["chmod", "+x", "/usr/local/tomcat/bin/startup.sh"]


#RUN ["cp", "/tmp/softpak_libs/librbengine.so.1", "/opt/urebal/engine_libs/"]
#RUN ["cp",  "/tmp/softpak_libs/RB_Bridge_DLL.so", "/opt/urebal/engine_libs/"]


RUN ["rm",  "-Rf", "/usr/local/tomcat/webapps/ROOT"]
RUN ["cp", "/tmp/softpak_libs/serviceweb.war", "/usr/local/tomcat/webapps/"]

EXPOSE 80 443 8080

ENTRYPOINT  ["/usr/local/tomcat/bin/startup.sh", "run"]
